a=input("Digite algo?")
print("O tipo primitivo desse valor é:", type(a))
print("Só tem espaçoes?", a.isspace())
print("É um número?", a.isnumeric())
print("É alfabetico? ", a.isalpha())
print("É alfanúmerico? {} ".format(a.isalnum()))
print("É maiscula?", a.isupper())
print("É minuscula?", a.islower())
print("É capitalizada?", a.istitle())